name: covidtracker
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_flutter: ^0.9.0
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
        - asset: fonts/NunitoSans-Italic.ttf
        - asset: fonts/NunitoSans-Bold.ttf
        - asset: fonts/NunitoSans-Light.ttf
        - asset: fonts/NunitoSans-ExtraLight.ttf
        - asset: fonts/NunitoSans-ExtraLightItalic.ttf
        - asset: fonts/NunitoSans-ExtraBold.ttf
        - asset: fonts/NunitoSans-ExtraBoldItalic.ttf
        - asset: fonts/NunitoSans-SemiBold.ttf
        - asset: fonts/NunitoSans-SemiBoldItalic.ttf
        - asset: fonts/NunitoSans-Black.ttf
        - asset: fonts/NunitoSans-BlackItalic.ttf